<a href="https://colab.research.google.com/github/Gowsalya-2006/Data-Analysis-Using-Python-Project/blob/main/DAY_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks = np.array([98,56,68,67])
print(marks[2])

68


Indexing & Slicing

In [ ]:
import numpy as np
marks = np.array([45,67,89,80])
print(marks[1:4])

[67 89 80]


Reshape & Transpose

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = arr.reshape(2,3)
print(b)
c=b.transpose()
print("\n",c)



[[1 2 3]
 [4 5 6]]


AGGEREGATION & AXIS OPERATION

In [ ]:
import numpy as np
marks = np.array([79,88,78,60])
average = np.mean(marks)
print(average)

78.5


In [ ]:
import numpy as np
salary=np.array([10000,20000,30000,40000,50000])
med=np.median(salary)
print(med)

In [ ]:
total=np.sum(marks)
print(total)