<a href="https://colab.research.google.com/github/Gowsalya-2006/Data-Analysis-Using-Python-Project/blob/main/Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
   num= int(input("Enter Numbers:"))
   print(num)
except:
  print("invaild Input")

Enter Numbers:123
123


Pratice:DAY-2
        Average Calculator with Function and Error Handling


In [ ]:
def calculate_average(x,y,z):
      return(x+y+z)/3
try:
   x = int(input("Enter first number:"))
   y = int(input("Enter second number:"))
   z = int(input("Enter third number:"))
   print("calculate_average =",calculate_average(x,y,z))
except ValueError:
    print("Invaild Input")

Enter first number:10
Enter second number:20
Enter third number:30
calculate_average = 20.0


Numby

In [ ]:
import numpy as np
marks = np.array([90,66,75,97])
print(marks)

[90 66 75 97]


In [ ]:
import numpy as np
students=np.array([
            [90,85],
            [78,93],
            [87,92,]
])
print(students)

[[90 85]
 [78 93]
 [87 92]]


In [ ]:
import numpy as np
add = np.array([[[3,5],[6,8],[12,13],[1,2]]])
print(add)


[[[ 3  5]
  [ 6  8]
  [12 13]
  [ 1  2]]]


Numpy Array Function

In [ ]:
#ZEROS
import numpy as np
arr=np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# ones
import numpy as np
arr=np.arrange(1,10)
print(arr)